server:
  port: 8050
spring:
  application:
    name: microservice-admin
  security:
    user:
      name: admin
      password: admin
  mail:
    host:
      mail.dae.org
  boot:
    admin:
      notify:
        mail:
          to:
            tengwei.chen@dae.org

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    #health-check-url-path: /actuator/health
    metadata-map:
      user.name: admin
      user.password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: trace
  path: ./logs



---
spring:
  profiles: ha1
server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer1:8762/eureka/

---
spring:
  profiles: ha2
server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer1:8762/eureka/
