server:
  port: 8761                    # 指定该Eureka实例的端口
spring:
  application:
    name: discovery
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true

---
spring:
  profiles: ha1                                 # 指定profile=peer1
server:
  port: 8761
eureka:
#  instance:
#    hostname: peer1                               # 指定当profile=peer1时，主机名是peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/      # 将自己注册到peer2这个Eureka上面去

---
spring:
  profiles: ha2
server:
  port: 8762
eureka:
#  instance:
#    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/